name: hesap_makinesi
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sensors_plus: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  fonts:
    - family: Nabla
      fonts:
        - asset: Fonts/Nabla-Regular.ttf
    - family: Honk
      fonts:
        - asset: Fonts/Honk-Regular.ttf
    - family: Courgette
      fonts:
        - asset: Fonts/Courgette-Regular.ttf
    - family: BadScript
      fonts:
        - asset: Fonts/BadScript-Regular.ttf
    - family: Hand
      fonts:
        - asset: Fonts/Hand.ttf

  uses-material-design: true

  assets:
    - resimler/autorenew.png
    - acılıs_ekranı/
